name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -
      - uses: actions/checkout@v4

      - name: List Keys
        shell: bash
        run: |
          gpg -K --keyid-format=long

      - name: Import GPG Private Key
        shell: bash
        run: |
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo -e "${{ secrets.ORG_GPG_PRIVATE_KEY }}" | gpg --import --batch
          for fpr in $(gpg --list-keys --with-colons | awk -F: '/fpr:/ {print $10}' | sort -u);
          do
            echo -e "5\\ny\\n" |  gpg --batch --command-fd 0 --expert --edit-key $fpr trust;
          done

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - env:
          OSSRH_PASSWORD: ${{ secrets.ORG_OSSRH_PASSWORD }}
          OSSRH_USER: ${{ secrets.ORG_OSSRH_USERNAME }}
        run: ./gradlew publish -Psigning.gnupg.passphrase="${{ secrets.ORG_GPG_PASSPHRASE }}"
