name: test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Docker image
        run: ./gradlew dockerBuild
      - name: Run tests
        run: ./gradlew test